name: Saludo usando variables
run-name: ¡Estoy aprendiendo a usar Variables!

on:
  workflow_dispatch:
    inputs:
      usuario:
        description: 'Nombre del usuario'
        required: true
        default: 'LUIS'
      edad:
        description: 'Edad del usuario'
        required: true
        default: '30'

env:
  CIUDAD: 'Madrid'
  SECRET_API_KEY: ${{ secrets.API_KEY }}  # Asegúrate de configurar este secreto en tu repositorio

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "Hola, mi nombre es ${{ github.event.inputs.usuario }} y tengo ${{ github.event.inputs.edad }} años."

  ciudad:
    runs-on: ubuntu-latest
    steps:
      - name: Información de la ciudad
        run: echo "Vivo en $CIUDAD."

  edad_en_meses:
    runs-on: ubuntu-latest
    steps:
      - name: Calcular edad en meses
        run: |
          meses=$(( ${{ github.event.inputs.edad }} * 12 ))
          echo "${{ github.event.inputs.usuario }} tiene $meses meses de edad."

  edad_categoria:
    runs-on: ubuntu-latest
    steps:
      - name: Determinar categoría de edad
        run: |
          if [ ${{ github.event.inputs.edad }} -lt 18 ]; then
            echo "${{ github.event.inputs.usuario }} es menor de edad."
          elif [ ${{ github.event.inputs.edad }} -ge 18 ] && [ ${{ github.event.inputs.edad }} -lt 65 ]; then
            echo "${{ github.event.inputs.usuario }} es adulto."
          else
            echo "${{ github.event.inputs.usuario }} es anciano."
          fi

  usar_secreto:
    runs-on: ubuntu-latest
    steps:
      - name: Usar la clave API secreta
        run: echo "La clave API es: $SECRET_API_KEY"
